services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "pp_security_app_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"